### ISSUE TITLE
Roadmap for `dashhd` v1 CLI

### ISSUE THREAD

**Issue by coolaj86** [dashhive/dashhd-cli#13]
- [x] seed to address range
- [x] seed to xprv
- [x] seed to xpub
- [x] xprv to address range
- [x] xpub to address range
- [x] Publish DashHD.js with nit fixes
   ```js
   //let DashHd = require("dashhd");
   let DashHd = require("../../dashhd.js");
   ```
- [x] Update docs with Zoomonics
- [x] Update Usage
- [x] Publish v1

**Comment by coolaj86** [comment]
implemented via #15
